// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class Product
{
    [Key]
    public int Id { get; set; }

    [Column("Ctegory_Id")]
    public int? CtegoryId { get; set; }

    [Column("Product_Name")]
    [StringLength(50)]
    public string ProductName { get; set; }

    [Column("Product_Description")]
    [StringLength(100)]
    public string ProductDescription { get; set; }

    public double? Price { get; set; }

    [Column("Image_Url")]
    [StringLength(1000)]
    public string ImageUrl { get; set; }

    [ForeignKey("CtegoryId")]
    [InverseProperty("Products")]
    [JsonIgnore]
    public virtual Category Ctegory { get; set; }

    [InverseProperty("Product")]
    [JsonIgnore]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}