// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class User
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("firstname")]
    [StringLength(50)]
    public string Firstname { get; set; }

    [Column("password")]
    [StringLength(50)]
    public string Password { get; set; }

    [Column("username")]
    [StringLength(50)]
    public string Username { get; set; }

    [Column("lastname")]
    [StringLength(50)]
    public string Lastname { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}